image: debian/sid
packages:
  - rustc
  - cargo
sources:
  - https://git.sr.ht/~moyanhao/bedrock-dataserver
tasks:
  - setup: |
      cd bedrock-dataserver
      CFG_RELEASE=stable CFG_RELEASE_CHANNEL=stable cargo install --path . --force --locked --features rustfmt,cargo-fmt
  - build: |
      cd bedrock-dataserver
      cargo build
