image: debian/sid
packages:
  - rustc
  - cargo
  - rustfmt
  - build-essential
  - curl
sources:
  - https://git.sr.ht/~moyanhao/bedrock-dataserver
tasks:
  - setup: |
      # cd bedrock-dataserver
      # CFG_RELEASE=stable CFG_RELEASE_CHANNEL=stable cargo install --path . --force --locked --features rustfmt,cargo-fmt
      # curl -y --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      # source ~/.bashrc
  - build: |
      cd bedrock-dataserver
      cargo build
